# Site settings
title: Doretox
motto: Infosec | hacker
email: doretox@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hacker and Infosec.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: doretox
github_username:  doretox

# Build settings
markdown: kramdown
